// Curated catalog of Maryland + Virginia higher-ed institutions for
// StudyHub's school + course directory. Used by bootstrapSchools.js
// to upsert rows into the School table on every boot.
//
// Detail fields (description, websiteUrl, latitude, longitude,
// enrollmentSize, foundedYear, mascot) are added 2026-05-16 to power:
//   - The location-aware school sort (haversine on lat/lng).
//   - The SchoolCourseDetailDrawer on /my-courses.
//
// Conventions:
//   - lat/lng come from the main campus, not satellite locations.
//   - description is 1-2 sentences, neutral, no rankings or admissions
//     stats (founder rule: no sensitive data, no legal exposure).
//   - enrollmentSize is rough total (undergrad + grad). Null when
//     reliable public number isn't available for non-flagship rows.
//   - foundedYear is the founding date of the institution as it exists
//     today (post-merger when applicable).
//   - mascot is the public mascot/identity tag — fun fact for the drawer.
//   - websiteUrl is the official institutional URL only.
//
// All sources: public USDOE IPEDS data + official college websites
// (used for non-sensitive fields only).

const SCHOOLS = [
  // ─────────────────────────────────────────────────────────────────
  // MARYLAND — Public 4-year (University System of Maryland)
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'University of Maryland, College Park',
    short: 'UMD',
    city: 'College Park',
    state: 'MD',
    schoolType: 'public',
    description:
      'Maryland’s flagship research university, with strong programs in computer science, engineering, business, and journalism. Member of the Big Ten conference and the University System of Maryland.',
    websiteUrl: 'https://www.umd.edu',
    latitude: 38.9869,
    longitude: -76.9426,
    enrollmentSize: 41000,
    foundedYear: 1856,
    mascot: 'Testudo the Terrapin',
  },
  {
    name: 'University of Maryland, Baltimore County',
    short: 'UMBC',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'Honors-style research university in the USM system known for science, engineering, and information technology programs and its Meyerhoff Scholars Program.',
    websiteUrl: 'https://www.umbc.edu',
    latitude: 39.2557,
    longitude: -76.7115,
    enrollmentSize: 13800,
    foundedYear: 1966,
    mascot: 'True Grit the Retriever',
  },
  {
    name: 'University of Maryland, Baltimore',
    short: 'UMB',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'Maryland’s public health, law, and human services university. Home to professional schools of medicine, law, dentistry, pharmacy, nursing, and social work.',
    websiteUrl: 'https://www.umaryland.edu',
    latitude: 39.2898,
    longitude: -76.6256,
    enrollmentSize: 7100,
    foundedYear: 1807,
    mascot: 'Touro the Bull',
  },
  {
    name: 'Towson University',
    short: 'TU',
    city: 'Towson',
    state: 'MD',
    schoolType: 'public',
    description:
      'Comprehensive metropolitan university in suburban Baltimore offering programs in business, education, communications, fine arts, and the sciences.',
    websiteUrl: 'https://www.towson.edu',
    latitude: 39.3939,
    longitude: -76.6097,
    enrollmentSize: 19500,
    foundedYear: 1866,
    mascot: 'Doc the Tiger',
  },
  {
    name: 'Morgan State University',
    short: 'Morgan',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'Designated Maryland’s public urban research university and one of the nation’s historically Black colleges and universities (HBCUs).',
    websiteUrl: 'https://www.morgan.edu',
    latitude: 39.3434,
    longitude: -76.5798,
    enrollmentSize: 9100,
    foundedYear: 1867,
    mascot: 'The Bear',
  },
  {
    name: 'Bowie State University',
    short: 'Bowie',
    city: 'Bowie',
    state: 'MD',
    schoolType: 'public',
    description:
      'The oldest HBCU in Maryland and a member of the University System of Maryland, offering programs in education, business, and computer science.',
    websiteUrl: 'https://www.bowiestate.edu',
    latitude: 39.0203,
    longitude: -76.7475,
    enrollmentSize: 6300,
    foundedYear: 1865,
    mascot: 'The Bulldog',
  },
  {
    name: 'Coppin State University',
    short: 'Coppin',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'HBCU in west Baltimore with a community-focused mission; strong programs in nursing, education, and social sciences.',
    websiteUrl: 'https://www.coppin.edu',
    latitude: 39.3128,
    longitude: -76.6588,
    enrollmentSize: 2300,
    foundedYear: 1900,
    mascot: 'The Eagle',
  },
  {
    name: 'Salisbury University',
    short: 'SU',
    city: 'Salisbury',
    state: 'MD',
    schoolType: 'public',
    description:
      'Comprehensive university on Maryland’s Eastern Shore offering programs in business, education, health professions, and the sciences.',
    websiteUrl: 'https://www.salisbury.edu',
    latitude: 38.3204,
    longitude: -75.6087,
    enrollmentSize: 7000,
    foundedYear: 1925,
    mascot: 'Sammy the Sea Gull',
  },
  {
    name: 'Frostburg State University',
    short: 'FSU',
    city: 'Frostburg',
    state: 'MD',
    schoolType: 'public',
    description:
      'Public regional university in western Maryland’s Appalachian mountains with strong programs in education, business, and environmental sciences.',
    websiteUrl: 'https://www.frostburg.edu',
    latitude: 39.6531,
    longitude: -78.929,
    enrollmentSize: 4400,
    foundedYear: 1898,
    mascot: 'The Bobcat',
  },
  {
    name: 'University of Baltimore',
    short: 'UBalt',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'USM institution focused on professional and graduate education with programs in business, law, and public affairs in downtown Baltimore.',
    websiteUrl: 'https://www.ubalt.edu',
    latitude: 39.3055,
    longitude: -76.6164,
    enrollmentSize: 3700,
    foundedYear: 1925,
    mascot: 'The Bee',
  },
  {
    name: 'University of Maryland Eastern Shore',
    short: 'UMES',
    city: 'Princess Anne',
    state: 'MD',
    schoolType: 'public',
    description:
      'HBCU and land-grant university with strong programs in agriculture, marine sciences, hospitality, and pharmacy.',
    websiteUrl: 'https://www.umes.edu',
    latitude: 38.2057,
    longitude: -75.6916,
    enrollmentSize: 2600,
    foundedYear: 1886,
    mascot: 'The Hawk',
  },
  {
    name: 'University of Maryland Global Campus',
    short: 'UMGC',
    city: 'Adelphi',
    state: 'MD',
    schoolType: 'public',
    description:
      'USM’s online-focused university serving adult learners and military students worldwide; offers undergraduate and graduate degrees fully online.',
    websiteUrl: 'https://www.umgc.edu',
    latitude: 38.9826,
    longitude: -76.9636,
    enrollmentSize: 58000,
    foundedYear: 1947,
    mascot: 'The Globe',
  },

  // MARYLAND — Other public
  {
    name: "St. Mary's College of Maryland",
    short: 'SMCM',
    city: "St. Mary's City",
    state: 'MD',
    schoolType: 'public',
    description:
      'Maryland’s public honors college, a small liberal arts institution on the lower Chesapeake known for undergraduate research.',
    websiteUrl: 'https://www.smcm.edu',
    latitude: 38.1893,
    longitude: -76.4324,
    enrollmentSize: 1500,
    foundedYear: 1840,
    mascot: 'The Seahawk',
  },
  {
    name: 'United States Naval Academy',
    short: 'USNA',
    city: 'Annapolis',
    state: 'MD',
    schoolType: 'public',
    description:
      'United States service academy in Annapolis preparing midshipmen for commissioned service in the Navy and Marine Corps. Tuition-free in exchange for service obligation.',
    websiteUrl: 'https://www.usna.edu',
    latitude: 38.9839,
    longitude: -76.4847,
    enrollmentSize: 4500,
    foundedYear: 1845,
    mascot: 'Bill the Goat',
  },

  // MARYLAND — Private 4-year
  {
    name: 'Johns Hopkins University',
    short: 'JHU',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
    description:
      'Private research university widely known for its medical school, public health programs, and applied physics laboratory. Founded as America’s first research university.',
    websiteUrl: 'https://www.jhu.edu',
    latitude: 39.3299,
    longitude: -76.6205,
    enrollmentSize: 30000,
    foundedYear: 1876,
    mascot: 'The Blue Jay',
  },
  {
    name: 'Loyola University Maryland',
    short: 'Loyola',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
    description:
      'Jesuit, Catholic university in north Baltimore offering programs in liberal arts, business, education, and the natural sciences.',
    websiteUrl: 'https://www.loyola.edu',
    latitude: 39.3496,
    longitude: -76.6126,
    enrollmentSize: 5700,
    foundedYear: 1852,
    mascot: 'Iggy the Greyhound',
  },
  {
    name: 'McDaniel College',
    short: 'McDaniel',
    city: 'Westminster',
    state: 'MD',
    schoolType: 'private',
    description:
      'Private liberal arts college in central Maryland with a hallmark curriculum spanning the humanities, sciences, and pre-professional programs.',
    websiteUrl: 'https://www.mcdaniel.edu',
    latitude: 39.5707,
    longitude: -77.0008,
    enrollmentSize: 2700,
    foundedYear: 1867,
    mascot: 'The Green Terror',
  },
  {
    name: 'Hood College',
    short: 'Hood',
    city: 'Frederick',
    state: 'MD',
    schoolType: 'private',
    description:
      'Private liberal arts and graduate institution in Frederick offering programs across the humanities, sciences, business, and education.',
    websiteUrl: 'https://www.hood.edu',
    latitude: 39.4202,
    longitude: -77.4034,
    enrollmentSize: 2000,
    foundedYear: 1893,
    mascot: 'The Blazer',
  },
  {
    name: 'Goucher College',
    short: 'Goucher',
    city: 'Towson',
    state: 'MD',
    schoolType: 'private',
    description:
      'Private liberal arts college in suburban Baltimore noted for its required study-abroad program and interdisciplinary curriculum.',
    websiteUrl: 'https://www.goucher.edu',
    latitude: 39.4084,
    longitude: -76.5868,
    enrollmentSize: 1700,
    foundedYear: 1885,
    mascot: 'The Gopher',
  },
  {
    name: "Mount St. Mary's University",
    short: 'MSM',
    city: 'Emmitsburg',
    state: 'MD',
    schoolType: 'private',
    description:
      'Catholic liberal arts university in the Catoctin Mountains of northern Maryland with programs in the humanities, sciences, business, and theology.',
    websiteUrl: 'https://msmary.edu',
    latitude: 39.7104,
    longitude: -77.3293,
    enrollmentSize: 2300,
    foundedYear: 1808,
    mascot: 'The Mountaineer',
  },
  {
    name: 'Washington College',
    short: 'WashCol',
    city: 'Chestertown',
    state: 'MD',
    schoolType: 'private',
    description:
      'Liberal arts college on Maryland’s Eastern Shore, founded with the support of George Washington and offering programs in the humanities, sciences, and writing.',
    websiteUrl: 'https://www.washcoll.edu',
    latitude: 39.2117,
    longitude: -76.0654,
    enrollmentSize: 1200,
    foundedYear: 1782,
    mascot: 'The Shoreman',
  },
  {
    name: 'Stevenson University',
    short: 'Stevenson',
    city: 'Stevenson',
    state: 'MD',
    schoolType: 'private',
    description:
      'Private career-focused university near Baltimore with programs in business, nursing, fashion, film, and forensic studies.',
    websiteUrl: 'https://www.stevenson.edu',
    latitude: 39.4179,
    longitude: -76.7686,
    enrollmentSize: 3100,
    foundedYear: 1947,
    mascot: 'The Mustang',
  },
  {
    name: 'Notre Dame of Maryland University',
    short: 'NDMU',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
    description:
      'Catholic university in north Baltimore offering programs in pharmacy, education, nursing, and the liberal arts.',
    websiteUrl: 'https://www.ndm.edu',
    latitude: 39.3554,
    longitude: -76.6113,
    enrollmentSize: 2000,
    foundedYear: 1895,
    mascot: 'The Gator',
  },
  {
    name: 'Maryland Institute College of Art',
    short: 'MICA',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
    description:
      'Independent, accredited college of art and design in Baltimore offering undergraduate and graduate degrees in fine arts, design, and art education.',
    websiteUrl: 'https://www.mica.edu',
    latitude: 39.3098,
    longitude: -76.6203,
    enrollmentSize: 3400,
    foundedYear: 1826,
    mascot: 'The Penguin',
  },
  {
    name: "St. John's College, Annapolis",
    short: 'StJohns',
    city: 'Annapolis',
    state: 'MD',
    schoolType: 'private',
    description:
      'Great Books college with a distinctive seminar-and-tutorial curriculum based on reading and discussing primary texts from the Western canon.',
    websiteUrl: 'https://www.sjc.edu',
    latitude: 38.984,
    longitude: -76.4885,
    enrollmentSize: 450,
    foundedYear: 1696,
    mascot: 'The Johnnie',
  },
  {
    name: 'Capitol Technology University',
    short: 'CapTech',
    city: 'Laurel',
    state: 'MD',
    schoolType: 'private',
    description:
      'STEM-focused private university with programs in cybersecurity, engineering, computer science, and astronautical engineering.',
    websiteUrl: 'https://www.captechu.edu',
    latitude: 39.1207,
    longitude: -76.7951,
    enrollmentSize: 800,
    foundedYear: 1927,
    mascot: 'Spike the Bulldog',
  },

  // MARYLAND — Community colleges
  {
    name: 'Montgomery College',
    short: 'MC',
    city: 'Rockville',
    state: 'MD',
    schoolType: 'public',
    description:
      'Multi-campus community college in Montgomery County serving the DC suburbs, with associate degrees and transfer programs across three locations.',
    websiteUrl: 'https://www.montgomerycollege.edu',
    latitude: 39.084,
    longitude: -77.1528,
    enrollmentSize: 50000,
    foundedYear: 1946,
    mascot: 'The Raptor',
  },
  {
    name: "Prince George's Community College",
    short: 'PGCC',
    city: 'Largo',
    state: 'MD',
    schoolType: 'public',
    description:
      'Public community college serving Prince George’s County with associate degrees, workforce training, and transfer programs.',
    websiteUrl: 'https://www.pgcc.edu',
    latitude: 38.8851,
    longitude: -76.8217,
    enrollmentSize: 25000,
    foundedYear: 1958,
    mascot: 'The Owl',
  },
  {
    name: 'Community College of Baltimore County',
    short: 'CCBC',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'Multi-campus community college serving Baltimore County with broad associate-degree and certificate programs.',
    websiteUrl: 'https://www.ccbcmd.edu',
    latitude: 39.4068,
    longitude: -76.7818,
    enrollmentSize: 56000,
    foundedYear: 1957,
    mascot: 'The Knight',
  },
  {
    name: 'Anne Arundel Community College',
    short: 'AACC',
    city: 'Arnold',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Anne Arundel County offering transfer programs to four-year institutions plus workforce certificates.',
    websiteUrl: 'https://www.aacc.edu',
    latitude: 39.0312,
    longitude: -76.5074,
    enrollmentSize: 22000,
    foundedYear: 1961,
    mascot: 'The Pioneer',
  },
  {
    name: 'Howard Community College',
    short: 'HCC',
    city: 'Columbia',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Howard County known for its arts programs, transfer pathways, and workforce development.',
    websiteUrl: 'https://www.howardcc.edu',
    latitude: 39.2103,
    longitude: -76.8688,
    enrollmentSize: 16000,
    foundedYear: 1970,
    mascot: 'The Dragon',
  },
  {
    name: 'Frederick Community College',
    short: 'FCC',
    city: 'Frederick',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Frederick County offering associate degrees, transfer programs, and workforce certifications.',
    websiteUrl: 'https://www.frederick.edu',
    latitude: 39.4504,
    longitude: -77.3835,
    enrollmentSize: 9000,
    foundedYear: 1957,
    mascot: 'The Cougar',
  },
  {
    name: 'Harford Community College',
    short: 'Harford',
    city: 'Bel Air',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Harford County serving the Baltimore-Washington corridor with transfer and career programs.',
    websiteUrl: 'https://www.harford.edu',
    latitude: 39.5234,
    longitude: -76.3535,
    enrollmentSize: 10000,
    foundedYear: 1957,
    mascot: 'The Fighting Owl',
  },
  {
    name: 'Carroll Community College',
    short: 'Carroll',
    city: 'Westminster',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Carroll County offering associate degrees, certificates, and dual-enrollment programs for high school students.',
    websiteUrl: 'https://www.carrollcc.edu',
    latitude: 39.5746,
    longitude: -77.0173,
    enrollmentSize: 5500,
    foundedYear: 1976,
    mascot: 'The Lynx',
  },
  {
    name: 'College of Southern Maryland',
    short: 'CSM',
    city: 'La Plata',
    state: 'MD',
    schoolType: 'public',
    description:
      'Multi-campus community college serving Charles, Calvert, and St. Mary’s counties with associate degrees and workforce training.',
    websiteUrl: 'https://www.csmd.edu',
    latitude: 38.5235,
    longitude: -76.9847,
    enrollmentSize: 9000,
    foundedYear: 1958,
    mascot: 'The Hawk',
  },
  {
    name: 'Baltimore City Community College',
    short: 'BCCC',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
    description:
      'Public community college in Baltimore offering associate degrees and workforce certificates with an urban-mission focus.',
    websiteUrl: 'https://www.bccc.edu',
    latitude: 39.3115,
    longitude: -76.6464,
    enrollmentSize: 4500,
    foundedYear: 1947,
    mascot: 'The Panther',
  },
  {
    name: 'Cecil College',
    short: 'Cecil',
    city: 'North East',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college serving Cecil County and the northern Chesapeake region with transfer and career programs.',
    websiteUrl: 'https://www.cecil.edu',
    latitude: 39.5712,
    longitude: -75.9583,
    enrollmentSize: 3000,
    foundedYear: 1968,
    mascot: 'The Seahawk',
  },
  {
    name: 'Chesapeake College',
    short: 'Chesapeake',
    city: 'Wye Mills',
    state: 'MD',
    schoolType: 'public',
    description:
      'Regional community college serving five counties on Maryland’s upper Eastern Shore.',
    websiteUrl: 'https://www.chesapeake.edu',
    latitude: 38.8939,
    longitude: -76.0717,
    enrollmentSize: 2300,
    foundedYear: 1965,
    mascot: 'The Skipjack',
  },
  {
    name: 'Garrett College',
    short: 'Garrett',
    city: 'McHenry',
    state: 'MD',
    schoolType: 'public',
    description:
      'Small community college in western Maryland’s mountain country offering associate degrees, adventure-sports programs, and workforce training.',
    websiteUrl: 'https://www.garrettcollege.edu',
    latitude: 39.5781,
    longitude: -79.3826,
    enrollmentSize: 700,
    foundedYear: 1971,
    mascot: 'The Laker',
  },
  {
    name: 'Hagerstown Community College',
    short: 'HagerstownCC',
    city: 'Hagerstown',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college in Washington County serving the I-81 corridor with associate degrees and workforce training.',
    websiteUrl: 'https://www.hagerstowncc.edu',
    latitude: 39.6418,
    longitude: -77.7191,
    enrollmentSize: 3500,
    foundedYear: 1946,
    mascot: 'The Hawk',
  },
  {
    name: 'Wor-Wic Community College',
    short: 'WorWic',
    city: 'Salisbury',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college on Maryland’s lower Eastern Shore serving Wicomico, Worcester, and Somerset counties.',
    websiteUrl: 'https://www.worwic.edu',
    latitude: 38.3501,
    longitude: -75.5613,
    enrollmentSize: 3000,
    foundedYear: 1975,
    mascot: 'The Hawk',
  },
  {
    name: 'Allegany College of Maryland',
    short: 'AlleganyCC',
    city: 'Cumberland',
    state: 'MD',
    schoolType: 'public',
    description:
      'Community college serving western Maryland with associate degrees in health sciences, transfer studies, and workforce certifications.',
    websiteUrl: 'https://www.allegany.edu',
    latitude: 39.6313,
    longitude: -78.7588,
    enrollmentSize: 2500,
    foundedYear: 1961,
    mascot: 'The Trojan',
  },

  // ─────────────────────────────────────────────────────────────────
  // VIRGINIA — Public 4-year
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'University of Virginia',
    short: 'UVA',
    city: 'Charlottesville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public research university founded by Thomas Jefferson, with top-ranked programs across the humanities, sciences, business, law, and medicine.',
    websiteUrl: 'https://www.virginia.edu',
    latitude: 38.0356,
    longitude: -78.5034,
    enrollmentSize: 25000,
    foundedYear: 1819,
    mascot: 'The Cavalier',
  },
  {
    name: 'Virginia Tech',
    short: 'VT',
    city: 'Blacksburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public land-grant research university with strong programs in engineering, agriculture, architecture, and business. ACC member.',
    websiteUrl: 'https://www.vt.edu',
    latitude: 37.2284,
    longitude: -80.4234,
    enrollmentSize: 38000,
    foundedYear: 1872,
    mascot: 'HokieBird',
  },
  {
    name: 'Virginia Commonwealth University',
    short: 'VCU',
    city: 'Richmond',
    state: 'VA',
    schoolType: 'public',
    description:
      'Urban research university in Richmond, with top-ranked arts and health-sciences programs and the affiliated VCU Health System.',
    websiteUrl: 'https://www.vcu.edu',
    latitude: 37.5479,
    longitude: -77.4521,
    enrollmentSize: 28000,
    foundedYear: 1838,
    mascot: 'Rodney the Ram',
  },
  {
    name: 'George Mason University',
    short: 'GMU',
    city: 'Fairfax',
    state: 'VA',
    schoolType: 'public',
    description:
      'Northern Virginia’s public research university with programs in business, computing, public policy, and the sciences.',
    websiteUrl: 'https://www.gmu.edu',
    latitude: 38.8298,
    longitude: -77.3074,
    enrollmentSize: 39000,
    foundedYear: 1949,
    mascot: 'The Patriot',
  },
  {
    name: 'William & Mary',
    short: 'WM',
    city: 'Williamsburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public research university chartered in 1693; one of the oldest institutions of higher education in the United States, with strong liberal arts and business programs.',
    websiteUrl: 'https://www.wm.edu',
    latitude: 37.2707,
    longitude: -76.7075,
    enrollmentSize: 8800,
    foundedYear: 1693,
    mascot: 'The Tribe',
  },
  {
    name: 'James Madison University',
    short: 'JMU',
    city: 'Harrisonburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public university in the Shenandoah Valley known for programs in business, education, and the health sciences.',
    websiteUrl: 'https://www.jmu.edu',
    latitude: 38.4374,
    longitude: -78.8694,
    enrollmentSize: 22000,
    foundedYear: 1908,
    mascot: 'Duke Dog',
  },
  {
    name: 'Old Dominion University',
    short: 'ODU',
    city: 'Norfolk',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public research university in the Hampton Roads region with strong engineering, business, and education programs.',
    websiteUrl: 'https://www.odu.edu',
    latitude: 36.886,
    longitude: -76.305,
    enrollmentSize: 23000,
    foundedYear: 1930,
    mascot: 'Big Blue the Lion',
  },
  {
    name: 'Virginia State University',
    short: 'VSU',
    city: 'Petersburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public HBCU and land-grant institution south of Richmond with programs in agriculture, business, education, and the sciences.',
    websiteUrl: 'https://www.vsu.edu',
    latitude: 37.2378,
    longitude: -77.4317,
    enrollmentSize: 4500,
    foundedYear: 1882,
    mascot: 'The Trojan',
  },
  {
    name: 'Norfolk State University',
    short: 'NSU',
    city: 'Norfolk',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public HBCU in Hampton Roads offering programs in business, computer science, education, and the social sciences.',
    websiteUrl: 'https://www.nsu.edu',
    latitude: 36.8484,
    longitude: -76.2613,
    enrollmentSize: 5500,
    foundedYear: 1935,
    mascot: 'The Spartan',
  },
  {
    name: 'Christopher Newport University',
    short: 'CNU',
    city: 'Newport News',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public liberal arts university on the Virginia Peninsula offering programs in the humanities, sciences, business, and leadership studies.',
    websiteUrl: 'https://cnu.edu',
    latitude: 37.0612,
    longitude: -76.4949,
    enrollmentSize: 4500,
    foundedYear: 1960,
    mascot: 'The Captain',
  },
  {
    name: 'Longwood University',
    short: 'Longwood',
    city: 'Farmville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public university in central Virginia with programs in business, education, communication, and the liberal arts.',
    websiteUrl: 'https://www.longwood.edu',
    latitude: 37.2982,
    longitude: -78.3953,
    enrollmentSize: 4500,
    foundedYear: 1839,
    mascot: 'The Lancer',
  },
  {
    name: 'Radford University',
    short: 'Radford',
    city: 'Radford',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public university in southwestern Virginia with programs in business, education, nursing, and the social sciences.',
    websiteUrl: 'https://www.radford.edu',
    latitude: 37.1374,
    longitude: -80.5478,
    enrollmentSize: 7500,
    foundedYear: 1910,
    mascot: 'The Highlander',
  },
  {
    name: 'University of Mary Washington',
    short: 'UMW',
    city: 'Fredericksburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public liberal arts university between Washington, DC, and Richmond with strong undergraduate research and humanities programs.',
    websiteUrl: 'https://www.umw.edu',
    latitude: 38.3032,
    longitude: -77.474,
    enrollmentSize: 4300,
    foundedYear: 1908,
    mascot: 'The Eagle',
  },
  {
    name: 'Virginia Military Institute',
    short: 'VMI',
    city: 'Lexington',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public senior military college in the Shenandoah Valley combining liberal-arts education with cadet training; all cadets follow a military lifestyle.',
    websiteUrl: 'https://www.vmi.edu',
    latitude: 37.7889,
    longitude: -79.4348,
    enrollmentSize: 1700,
    foundedYear: 1839,
    mascot: 'The Keydet',
  },
  {
    name: "University of Virginia's College at Wise",
    short: 'UVAWise',
    city: 'Wise',
    state: 'VA',
    schoolType: 'public',
    description:
      'Public liberal arts college in southwestern Virginia, part of the University of Virginia system, with programs in the humanities, sciences, and business.',
    websiteUrl: 'https://www.uvawise.edu',
    latitude: 36.978,
    longitude: -82.581,
    enrollmentSize: 2000,
    foundedYear: 1954,
    mascot: 'The Cavalier',
  },

  // VIRGINIA — Private 4-year
  {
    name: 'University of Richmond',
    short: 'UR',
    city: 'Richmond',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts university in Richmond combining traditional undergraduate programs with the Robins School of Business and a law school.',
    websiteUrl: 'https://www.richmond.edu',
    latitude: 37.5751,
    longitude: -77.5379,
    enrollmentSize: 4000,
    foundedYear: 1830,
    mascot: 'The Spider',
  },
  {
    name: 'Washington and Lee University',
    short: 'WLU',
    city: 'Lexington',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts university in the Shenandoah Valley with an honor system, a law school, and a strong commitment to undergraduate teaching.',
    websiteUrl: 'https://www.wlu.edu',
    latitude: 37.7872,
    longitude: -79.4435,
    enrollmentSize: 2200,
    foundedYear: 1749,
    mascot: 'The General',
  },
  {
    name: 'Liberty University',
    short: 'Liberty',
    city: 'Lynchburg',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private Christian research university in Lynchburg offering programs on a large residential campus and one of the country’s largest online programs.',
    websiteUrl: 'https://www.liberty.edu',
    latitude: 37.3531,
    longitude: -79.1709,
    enrollmentSize: 100000,
    foundedYear: 1971,
    mascot: 'Sparky the Eagle',
  },
  {
    name: 'Hampton University',
    short: 'Hampton',
    city: 'Hampton',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private HBCU on the Hampton Roads waterfront with strong programs in business, journalism, nursing, and the sciences.',
    websiteUrl: 'https://www.hamptonu.edu',
    latitude: 37.022,
    longitude: -76.337,
    enrollmentSize: 3700,
    foundedYear: 1868,
    mascot: 'The Pirate',
  },
  {
    name: 'Marymount University',
    short: 'Marymount',
    city: 'Arlington',
    state: 'VA',
    schoolType: 'private',
    description:
      'Catholic university in Arlington, just outside Washington, DC, with programs in business, health sciences, education, and design.',
    websiteUrl: 'https://www.marymount.edu',
    latitude: 38.9035,
    longitude: -77.1063,
    enrollmentSize: 3500,
    foundedYear: 1950,
    mascot: 'The Saint',
  },
  {
    name: 'Shenandoah University',
    short: 'Shenandoah',
    city: 'Winchester',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private university in the Shenandoah Valley with a noted conservatory of music and programs in health sciences, business, and the arts.',
    websiteUrl: 'https://www.su.edu',
    latitude: 39.1632,
    longitude: -78.1469,
    enrollmentSize: 4500,
    foundedYear: 1875,
    mascot: 'The Hornet',
  },
  {
    name: 'Roanoke College',
    short: 'Roanoke',
    city: 'Salem',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts college in the Roanoke Valley with programs across the humanities, sciences, business, and education.',
    websiteUrl: 'https://www.roanoke.edu',
    latitude: 37.291,
    longitude: -80.0573,
    enrollmentSize: 2000,
    foundedYear: 1842,
    mascot: 'The Maroon',
  },
  {
    name: 'Randolph-Macon College',
    short: 'RMC',
    city: 'Ashland',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts college north of Richmond with programs in the humanities, sciences, business, and pre-professional studies.',
    websiteUrl: 'https://www.rmc.edu',
    latitude: 37.7559,
    longitude: -77.4789,
    enrollmentSize: 1500,
    foundedYear: 1830,
    mascot: 'The Yellow Jacket',
  },
  {
    name: 'University of Lynchburg',
    short: 'Lynchburg',
    city: 'Lynchburg',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private university in central Virginia with programs in health sciences, business, education, and the liberal arts.',
    websiteUrl: 'https://www.lynchburg.edu',
    latitude: 37.398,
    longitude: -79.1853,
    enrollmentSize: 2700,
    foundedYear: 1903,
    mascot: 'The Hornet',
  },
  {
    name: 'Hollins University',
    short: 'Hollins',
    city: 'Roanoke',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts university with a women’s undergraduate program and co-educational graduate programs, including a noted MFA in creative writing.',
    websiteUrl: 'https://www.hollins.edu',
    latitude: 37.3438,
    longitude: -79.9395,
    enrollmentSize: 700,
    foundedYear: 1842,
    mascot: 'The Lioness',
  },
  {
    name: 'Bridgewater College',
    short: 'Bridgewater',
    city: 'Bridgewater',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts college in the Shenandoah Valley affiliated with the Church of the Brethren, with programs in the humanities, sciences, and business.',
    websiteUrl: 'https://www.bridgewater.edu',
    latitude: 38.3835,
    longitude: -78.9764,
    enrollmentSize: 1400,
    foundedYear: 1880,
    mascot: 'The Eagle',
  },
  {
    name: 'Hampden-Sydney College',
    short: 'HSC',
    city: 'Hampden Sydney',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private men’s liberal arts college in central Virginia with an honor code and a curriculum centered on the humanities and rhetoric.',
    websiteUrl: 'https://www.hsc.edu',
    latitude: 37.241,
    longitude: -78.4607,
    enrollmentSize: 900,
    foundedYear: 1775,
    mascot: 'The Tiger',
  },
  {
    name: 'Regent University',
    short: 'Regent',
    city: 'Virginia Beach',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private Christian research university with programs in law, divinity, communication, business, and the sciences.',
    websiteUrl: 'https://www.regent.edu',
    latitude: 36.8385,
    longitude: -76.1864,
    enrollmentSize: 11000,
    foundedYear: 1977,
    mascot: 'The Royal',
  },
  {
    name: 'Sweet Briar College',
    short: 'SweetBriar',
    city: 'Sweet Briar',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private women’s liberal arts college in central Virginia with programs in engineering, the sciences, the humanities, and equestrian studies.',
    websiteUrl: 'https://sbc.edu',
    latitude: 37.5572,
    longitude: -79.0838,
    enrollmentSize: 450,
    foundedYear: 1901,
    mascot: 'The Vixen',
  },
  {
    name: 'Mary Baldwin University',
    short: 'MaryBaldwin',
    city: 'Staunton',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private university in the Shenandoah Valley with a women’s undergraduate college and co-educational graduate programs in education, business, and health sciences.',
    websiteUrl: 'https://www.marybaldwin.edu',
    latitude: 38.149,
    longitude: -79.0717,
    enrollmentSize: 1700,
    foundedYear: 1842,
    mascot: 'The Squirrel',
  },
  {
    name: 'Emory & Henry College',
    short: 'EmoryHenry',
    city: 'Emory',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts college in southwestern Virginia with programs in the humanities, sciences, business, and health sciences.',
    websiteUrl: 'https://www.ehc.edu',
    latitude: 36.7995,
    longitude: -81.8401,
    enrollmentSize: 1100,
    foundedYear: 1836,
    mascot: 'The Wasp',
  },
  {
    name: 'Eastern Mennonite University',
    short: 'EMU',
    city: 'Harrisonburg',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private Mennonite university in the Shenandoah Valley with programs in peacebuilding, nursing, business, and the liberal arts.',
    websiteUrl: 'https://emu.edu',
    latitude: 38.4814,
    longitude: -78.8666,
    enrollmentSize: 1700,
    foundedYear: 1917,
    mascot: 'The Royal',
  },
  {
    name: 'Virginia Wesleyan University',
    short: 'VWU',
    city: 'Virginia Beach',
    state: 'VA',
    schoolType: 'private',
    description:
      'Private liberal arts university in the Hampton Roads region with programs in the humanities, business, and the sciences.',
    websiteUrl: 'https://www.vwu.edu',
    latitude: 36.8868,
    longitude: -76.1843,
    enrollmentSize: 1500,
    foundedYear: 1961,
    mascot: 'The Marlin',
  },

  // VIRGINIA — Virginia Community College System
  {
    name: 'Northern Virginia Community College',
    short: 'NOVA',
    city: 'Annandale',
    state: 'VA',
    schoolType: 'public',
    description:
      'Multi-campus community college serving Northern Virginia and the DC metro area; one of the largest community colleges in the United States.',
    websiteUrl: 'https://www.nvcc.edu',
    latitude: 38.8307,
    longitude: -77.1839,
    enrollmentSize: 75000,
    foundedYear: 1965,
    mascot: 'The Nighthawk',
  },
  {
    name: 'Tidewater Community College',
    short: 'TCC',
    city: 'Norfolk',
    state: 'VA',
    schoolType: 'public',
    description:
      'Multi-campus community college serving the Hampton Roads region with associate degrees, transfer programs, and workforce training.',
    websiteUrl: 'https://www.tcc.edu',
    latitude: 36.8475,
    longitude: -76.2949,
    enrollmentSize: 30000,
    foundedYear: 1968,
    mascot: 'The Gator',
  },
  {
    name: 'Virginia Western Community College',
    short: 'VirginiaWestern',
    city: 'Roanoke',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in the Roanoke Valley serving southwestern Virginia with associate degrees and workforce certifications.',
    websiteUrl: 'https://www.virginiawestern.edu',
    latitude: 37.2575,
    longitude: -79.9544,
    enrollmentSize: 8000,
    foundedYear: 1966,
    mascot: 'The Knight',
  },
  {
    name: 'J. Sargeant Reynolds Community College',
    short: 'Reynolds',
    city: 'Richmond',
    state: 'VA',
    schoolType: 'public',
    description:
      'Multi-campus community college in the Richmond region offering transfer programs, workforce certifications, and adult basic education.',
    websiteUrl: 'https://www.reynolds.edu',
    latitude: 37.5599,
    longitude: -77.4716,
    enrollmentSize: 16000,
    foundedYear: 1972,
    mascot: 'The Jaguar',
  },
  {
    name: 'Germanna Community College',
    short: 'Germanna',
    city: 'Locust Grove',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in the Fredericksburg region serving central and northern Virginia with associate degrees and workforce programs.',
    websiteUrl: 'https://www.germanna.edu',
    latitude: 38.3461,
    longitude: -77.7325,
    enrollmentSize: 9500,
    foundedYear: 1970,
    mascot: 'The Wolf',
  },
  {
    name: 'Blue Ridge Community College',
    short: 'BlueRidge',
    city: 'Weyers Cave',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in the Shenandoah Valley serving the central Valley region with transfer and career programs.',
    websiteUrl: 'https://www.brcc.edu',
    latitude: 38.2924,
    longitude: -78.913,
    enrollmentSize: 4500,
    foundedYear: 1967,
    mascot: 'The Tiger',
  },
  {
    name: 'Central Virginia Community College',
    short: 'CVCC',
    city: 'Lynchburg',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving central Virginia and the Lynchburg region with associate degrees and workforce training.',
    websiteUrl: 'https://www.centralvirginia.edu',
    latitude: 37.4032,
    longitude: -79.1559,
    enrollmentSize: 4500,
    foundedYear: 1966,
    mascot: 'The Knight',
  },
  {
    name: 'Piedmont Virginia Community College',
    short: 'PVCC',
    city: 'Charlottesville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in the Charlottesville region offering transfer programs, workforce certifications, and adult education.',
    websiteUrl: 'https://www.pvcc.edu',
    latitude: 37.9889,
    longitude: -78.4793,
    enrollmentSize: 6000,
    foundedYear: 1972,
    mascot: 'The Eagle',
  },
  {
    name: 'Laurel Ridge Community College',
    short: 'LaurelRidge',
    city: 'Middletown',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving Virginia’s northern Shenandoah Valley (formerly Lord Fairfax Community College).',
    websiteUrl: 'https://www.laurelridge.edu',
    latitude: 39.0345,
    longitude: -78.2776,
    enrollmentSize: 6500,
    foundedYear: 1970,
    mascot: 'The Mountain Lion',
  },
  {
    name: 'New River Community College',
    short: 'NewRiver',
    city: 'Dublin',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in southwestern Virginia serving the New River Valley with associate degrees and workforce certifications.',
    websiteUrl: 'https://www.nr.edu',
    latitude: 37.1018,
    longitude: -80.6862,
    enrollmentSize: 4000,
    foundedYear: 1969,
    mascot: 'The Knight',
  },
  {
    name: 'Virginia Peninsula Community College',
    short: 'VirginiaPeninsula',
    city: 'Hampton',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college on the Virginia Peninsula (formerly Thomas Nelson Community College) serving Hampton Roads with transfer and career programs.',
    websiteUrl: 'https://www.vpcc.edu',
    latitude: 37.0641,
    longitude: -76.4257,
    enrollmentSize: 9000,
    foundedYear: 1968,
    mascot: 'The Gator',
  },
  {
    name: 'Rappahannock Community College',
    short: 'Rappahannock',
    city: 'Glenns',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in eastern Virginia’s Middle Peninsula and Northern Neck region with associate degrees and workforce programs.',
    websiteUrl: 'https://www.rappahannock.edu',
    latitude: 37.6878,
    longitude: -76.557,
    enrollmentSize: 2500,
    foundedYear: 1970,
    mascot: 'The Riverhawk',
  },
  {
    name: 'Southwest Virginia Community College',
    short: 'SWVCC',
    city: 'Cedar Bluff',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving southwestern Virginia’s coalfield region with associate degrees and workforce certifications.',
    websiteUrl: 'https://www.sw.edu',
    latitude: 37.0934,
    longitude: -81.7656,
    enrollmentSize: 2500,
    foundedYear: 1967,
    mascot: 'The Falcon',
  },
  {
    name: 'Mountain Empire Community College',
    short: 'MountainEmpire',
    city: 'Big Stone Gap',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in far southwestern Virginia serving Lee, Scott, Wise, and Dickenson counties.',
    websiteUrl: 'https://www.mecc.edu',
    latitude: 36.8665,
    longitude: -82.7468,
    enrollmentSize: 2700,
    foundedYear: 1972,
    mascot: 'The Cougar',
  },
  {
    name: 'Wytheville Community College',
    short: 'Wytheville',
    city: 'Wytheville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in southwestern Virginia’s I-77/I-81 corridor with associate degrees and workforce programs.',
    websiteUrl: 'https://www.wcc.vccs.edu',
    latitude: 36.957,
    longitude: -81.0846,
    enrollmentSize: 2200,
    foundedYear: 1963,
    mascot: 'The Storm',
  },
  {
    name: 'Patrick & Henry Community College',
    short: 'PatrickHenry',
    city: 'Martinsville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in southern Virginia serving Henry and Patrick counties with associate degrees and workforce training.',
    websiteUrl: 'https://www.patrickhenry.edu',
    latitude: 36.6843,
    longitude: -79.8725,
    enrollmentSize: 2700,
    foundedYear: 1962,
    mascot: 'The Patriot',
  },
  {
    name: 'Southside Virginia Community College',
    short: 'Southside',
    city: 'Alberta',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving southside Virginia with associate degrees, workforce certifications, and adult basic education.',
    websiteUrl: 'https://www.southside.edu',
    latitude: 36.866,
    longitude: -77.881,
    enrollmentSize: 4500,
    foundedYear: 1970,
    mascot: 'The Panther',
  },
  {
    name: 'Danville Community College',
    short: 'Danville',
    city: 'Danville',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving southern Virginia’s Dan River region with associate degrees and workforce programs.',
    websiteUrl: 'https://www.danville.edu',
    latitude: 36.5912,
    longitude: -79.4117,
    enrollmentSize: 2700,
    foundedYear: 1936,
    mascot: 'The Knight',
  },
  {
    name: 'Eastern Shore Community College',
    short: 'EasternShoreVA',
    city: 'Melfa',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving Virginia’s Eastern Shore with associate degrees and workforce programs.',
    websiteUrl: 'https://www.es.vccs.edu',
    latitude: 37.6404,
    longitude: -75.7472,
    enrollmentSize: 500,
    foundedYear: 1971,
    mascot: 'The Marlin',
  },
  {
    name: 'Paul D. Camp Community College',
    short: 'PDCCC',
    city: 'Franklin',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college serving southside Hampton Roads with associate degrees and workforce certifications.',
    websiteUrl: 'https://www.pdc.edu',
    latitude: 36.6776,
    longitude: -76.9224,
    enrollmentSize: 1400,
    foundedYear: 1971,
    mascot: 'The Hurricane',
  },
  {
    name: 'Virginia Highlands Community College',
    short: 'VirginiaHighlands',
    city: 'Abingdon',
    state: 'VA',
    schoolType: 'public',
    description:
      'Community college in southwestern Virginia serving the Abingdon region with associate degrees and workforce programs.',
    websiteUrl: 'https://www.vhcc.edu',
    latitude: 36.7065,
    longitude: -81.9954,
    enrollmentSize: 2400,
    foundedYear: 1967,
    mascot: 'The Cardinal',
  },
]

module.exports = { SCHOOLS }
