const SCHOOLS = [
  // PUBLIC 4-YEAR (University System of Maryland)
  { name: 'University of Maryland, College Park', short: 'UMD', city: 'College Park', state: 'MD', schoolType: 'public' },
  { name: 'University of Maryland, Baltimore County', short: 'UMBC', city: 'Baltimore', state: 'MD', schoolType: 'public' },
  { name: 'Towson University', short: 'TU', city: 'Towson', state: 'MD', schoolType: 'public' },
  { name: 'Morgan State University', short: 'Morgan', city: 'Baltimore', state: 'MD', schoolType: 'public' },
  { name: 'Bowie State University', short: 'Bowie', city: 'Bowie', state: 'MD', schoolType: 'public' },
  { name: 'Coppin State University', short: 'Coppin', city: 'Baltimore', state: 'MD', schoolType: 'public' },
  { name: 'Salisbury University', short: 'SU', city: 'Salisbury', state: 'MD', schoolType: 'public' },
  { name: 'Frostburg State University', short: 'FSU', city: 'Frostburg', state: 'MD', schoolType: 'public' },
  { name: 'University of Baltimore', short: 'UBalt', city: 'Baltimore', state: 'MD', schoolType: 'public' },
  { name: 'University of Maryland Eastern Shore', short: 'UMES', city: 'Princess Anne', state: 'MD', schoolType: 'public' },
  { name: 'University of Maryland Global Campus', short: 'UMGC', city: 'Adelphi', state: 'MD', schoolType: 'public' },

  // OTHER PUBLIC
  { name: "St. Mary's College of Maryland", short: 'SMCM', city: "St. Mary's City", state: 'MD', schoolType: 'public' },
  { name: 'United States Naval Academy', short: 'USNA', city: 'Annapolis', state: 'MD', schoolType: 'public' },

  // PRIVATE
  { name: 'Johns Hopkins University', short: 'JHU', city: 'Baltimore', state: 'MD', schoolType: 'private' },
  { name: 'Loyola University Maryland', short: 'Loyola', city: 'Baltimore', state: 'MD', schoolType: 'private' },
  { name: 'McDaniel College', short: 'McDaniel', city: 'Westminster', state: 'MD', schoolType: 'private' },
  { name: 'Hood College', short: 'Hood', city: 'Frederick', state: 'MD', schoolType: 'private' },
  { name: 'Goucher College', short: 'Goucher', city: 'Towson', state: 'MD', schoolType: 'private' },
  { name: "Mount St. Mary's University", short: 'MSM', city: 'Emmitsburg', state: 'MD', schoolType: 'private' },
  { name: 'Washington College', short: 'WashCol', city: 'Chestertown', state: 'MD', schoolType: 'private' },
  { name: 'Stevenson University', short: 'Stevenson', city: 'Stevenson', state: 'MD', schoolType: 'private' },
  { name: 'Notre Dame of Maryland University', short: 'NDMU', city: 'Baltimore', state: 'MD', schoolType: 'private' },

  // COMMUNITY COLLEGES
  { name: 'Montgomery College', short: 'MC', city: 'Rockville', state: 'MD', schoolType: 'public' },
  { name: "Prince George's Community College", short: 'PGCC', city: 'Largo', state: 'MD', schoolType: 'public' },
  { name: 'Community College of Baltimore County', short: 'CCBC', city: 'Baltimore', state: 'MD', schoolType: 'public' },
  { name: 'Anne Arundel Community College', short: 'AACC', city: 'Arnold', state: 'MD', schoolType: 'public' },
  { name: 'Howard Community College', short: 'HCC', city: 'Columbia', state: 'MD', schoolType: 'public' },
  { name: 'Frederick Community College', short: 'FCC', city: 'Frederick', state: 'MD', schoolType: 'public' },
  { name: 'Harford Community College', short: 'Harford', city: 'Bel Air', state: 'MD', schoolType: 'public' },
  { name: 'Carroll Community College', short: 'Carroll', city: 'Westminster', state: 'MD', schoolType: 'public' },
  { name: 'College of Southern Maryland', short: 'CSM', city: 'La Plata', state: 'MD', schoolType: 'public' },
]

const COURSES = {
  // UNIVERSITY OF MARYLAND, COLLEGE PARK (Major Research University - 70+ courses)
  UMD: [
    // Computer Science (16 courses)
    { name: 'Introduction to C Programming', code: 'CMSC106', department: 'Computer Science' },
    { name: 'Object-Oriented Programming I', code: 'CMSC131', department: 'Computer Science' },
    { name: 'Object-Oriented Programming II', code: 'CMSC132', department: 'Computer Science' },
    { name: 'Introduction to Computer Systems', code: 'CMSC216', department: 'Computer Science' },
    { name: 'Discrete Structures', code: 'CMSC250', department: 'Computer Science' },
    { name: 'Introduction to Data Science', code: 'CMSC320', department: 'Computer Science' },
    { name: 'Organization of Programming Languages', code: 'CMSC330', department: 'Computer Science' },
    { name: 'Web Application Development', code: 'CMSC335', department: 'Computer Science' },
    { name: 'Algorithms', code: 'CMSC351', department: 'Computer Science' },
    { name: 'Computer Graphics', code: 'CMSC425', department: 'Computer Science' },
    { name: 'Human-Computer Interaction', code: 'CMSC434', department: 'Computer Science' },
    { name: 'Database Management Systems', code: 'CMSC461', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'CMSC421', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'CMSC422', department: 'Computer Science' },
    { name: 'Computer Networks', code: 'CMSC414', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'CMSC435', department: 'Computer Science' },

    // Mathematics (14 courses)
    { name: 'Precalculus', code: 'MATH115', department: 'Mathematics' },
    { name: 'Elementary Calculus I', code: 'MATH120', department: 'Mathematics' },
    { name: 'Elementary Calculus II', code: 'MATH121', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH140', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH141', department: 'Mathematics' },
    { name: 'Calculus III', code: 'MATH241', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH240', department: 'Mathematics' },
    { name: 'Discrete Mathematics for Life Sciences', code: 'MATH135', department: 'Mathematics' },
    { name: 'Applied Mathematics for Engineering', code: 'MATH246', department: 'Mathematics' },
    { name: 'Abstract Algebra I', code: 'MATH310', department: 'Mathematics' },
    { name: 'Real Analysis I', code: 'MATH320', department: 'Mathematics' },
    { name: 'Complex Analysis', code: 'MATH410', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'MATH341', department: 'Mathematics' },
    { name: 'Numerical Methods', code: 'MATH461', department: 'Mathematics' },

    // Physics (12 courses)
    { name: 'Physics of Music', code: 'PHYS102', department: 'Physics' },
    { name: 'Light and Photography', code: 'PHYS106', department: 'Physics' },
    { name: 'Physics in the Modern World', code: 'PHYS111', department: 'Physics' },
    { name: 'Fundamentals of Physics I', code: 'PHYS121', department: 'Physics' },
    { name: 'Fundamentals of Physics II', code: 'PHYS122', department: 'Physics' },
    { name: 'University Physics I', code: 'PHYS131', department: 'Physics' },
    { name: 'University Physics II', code: 'PHYS132', department: 'Physics' },
    { name: 'Physics for Engineering I', code: 'PHYS141', department: 'Physics' },
    { name: 'Physics for Engineering II', code: 'PHYS142', department: 'Physics' },
    { name: 'Modern Physics', code: 'PHYS260', department: 'Physics' },
    { name: 'Optics', code: 'PHYS320', department: 'Physics' },
    { name: 'Thermodynamics', code: 'PHYS401', department: 'Physics' },

    // Chemistry (12 courses)
    { name: 'Chemistry I - General Chemistry', code: 'CHEM131', department: 'Chemistry' },
    { name: 'General Chemistry I Laboratory', code: 'CHEM132', department: 'Chemistry' },
    { name: 'General Chemistry for Engineers', code: 'CHEM135', department: 'Chemistry' },
    { name: 'Principles of General Chemistry', code: 'CHEM146', department: 'Chemistry' },
    { name: 'Chemistry II - Organic Chemistry', code: 'CHEM231', department: 'Chemistry' },
    { name: 'Organic Chemistry Laboratory', code: 'CHEM232', department: 'Chemistry' },
    { name: 'Organic Chemistry Reaction Mechanisms', code: 'CHEM341', department: 'Chemistry' },
    { name: 'Physical Chemistry I', code: 'CHEM351', department: 'Chemistry' },
    { name: 'Analytical Chemistry', code: 'CHEM421', department: 'Chemistry' },
    { name: 'Biochemistry I', code: 'CHEM431', department: 'Chemistry' },
    { name: 'Biochemistry II', code: 'CHEM432', department: 'Chemistry' },
    { name: 'Inorganic Chemistry', code: 'CHEM441', department: 'Chemistry' },

    // Biology (12 courses)
    { name: 'The World of Biology', code: 'BSCI103', department: 'Biology' },
    { name: 'Insects', code: 'BSCI120', department: 'Biology' },
    { name: 'Plant Biology for Non-Science Students', code: 'BSCI124', department: 'Biology' },
    { name: 'General Biology I', code: 'BSCI170', department: 'Biology' },
    { name: 'General Biology II', code: 'BSCI171', department: 'Biology' },
    { name: 'Cell Biology and Molecular Genetics', code: 'BSCI272', department: 'Biology' },
    { name: 'Genetics', code: 'BSCI370', department: 'Biology' },
    { name: 'Ecology', code: 'BSCI330', department: 'Biology' },
    { name: 'Evolution', code: 'BSCI340', department: 'Biology' },
    { name: 'Molecular Biology', code: 'BSCI375', department: 'Biology' },
    { name: 'Physiology', code: 'BSCI380', department: 'Biology' },
    { name: 'Developmental Biology', code: 'BSCI420', department: 'Biology' },

    // English (14 courses)
    { name: 'Academic Writing', code: 'ENGL101', department: 'English' },
    { name: 'Shakespeare and Identity', code: 'ENGL120', department: 'English' },
    { name: 'Renaissance Lyric and Song', code: 'ENGL121', department: 'English' },
    { name: 'Why Poetry Matters', code: 'ENGL125', department: 'English' },
    { name: 'Why Fiction Matters', code: 'ENGL126', department: 'English' },
    { name: 'British Literature I', code: 'ENGL242', department: 'English' },
    { name: 'British Literature II', code: 'ENGL243', department: 'English' },
    { name: 'American Literature I', code: 'ENGL245', department: 'English' },
    { name: 'American Literature II', code: 'ENGL246', department: 'English' },
    { name: 'World Literature I', code: 'ENGL248', department: 'English' },
    { name: 'World Literature II', code: 'ENGL249', department: 'English' },
    { name: 'Technical Writing', code: 'ENGL310', department: 'English' },
    { name: 'Creative Writing: Poetry', code: 'ENGL391', department: 'English' },
    { name: 'Creative Writing: Fiction', code: 'ENGL392', department: 'English' },

    // History (13 courses)
    { name: 'American Jewish Experience', code: 'HIST106', department: 'History' },
    { name: 'The Ancient World', code: 'HIST110', department: 'History' },
    { name: 'The Medieval World', code: 'HIST111', department: 'History' },
    { name: 'Early Modern Europe', code: 'HIST112', department: 'History' },
    { name: 'Modern Europe', code: 'HIST113', department: 'History' },
    { name: 'Colonial America', code: 'HIST121', department: 'History' },
    { name: 'Revolutionary America', code: 'HIST122', department: 'History' },
    { name: 'Civil War Era America', code: 'HIST123', department: 'History' },
    { name: 'Modern America', code: 'HIST124', department: 'History' },
    { name: 'Ancient China', code: 'HIST131', department: 'History' },
    { name: 'Modern East Asia', code: 'HIST132', department: 'History' },
    { name: 'Latin American History', code: 'HIST150', department: 'History' },
    { name: 'African History', code: 'HIST160', department: 'History' },

    // Psychology (10 courses)
    { name: 'Introduction to Psychology', code: 'PSYC100', department: 'Psychology' },
    { name: 'Statistical Methods in Psychology', code: 'PSYC200', department: 'Psychology' },
    { name: 'Introduction to Neuroscience', code: 'PSYC202', department: 'Psychology' },
    { name: 'Personality and Temperament', code: 'PSYC210', department: 'Psychology' },
    { name: 'Social Psychology', code: 'PSYC221', department: 'Psychology' },
    { name: 'Developmental Psychology', code: 'PSYC230', department: 'Psychology' },
    { name: 'Sensation and Perception', code: 'PSYC330', department: 'Psychology' },
    { name: 'Abnormal Psychology', code: 'PSYC350', department: 'Psychology' },
    { name: 'Cognitive Psychology', code: 'PSYC370', department: 'Psychology' },
    { name: 'Psychopharmacology', code: 'PSYC400', department: 'Psychology' },

    // Economics (10 courses)
    { name: 'Thinking Like an Economist', code: 'ECON111', department: 'Economics' },
    { name: 'Inequality: Determinants and Policy', code: 'ECON175', department: 'Economics' },
    { name: 'Pricing the Environment', code: 'ECON181', department: 'Economics' },
    { name: 'Energy: Crisis or Breakthrough', code: 'ECON185', department: 'Economics' },
    { name: 'Principles of Microeconomics', code: 'ECON200', department: 'Economics' },
    { name: 'Principles of Macroeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Intermediate Microeconomic Theory', code: 'ECON301', department: 'Economics' },
    { name: 'Intermediate Macroeconomic Theory', code: 'ECON303', department: 'Economics' },
    { name: 'International Economics', code: 'ECON320', department: 'Economics' },
    { name: 'Labor Economics', code: 'ECON325', department: 'Economics' },

    // Business (10 courses)
    { name: 'Introduction to Business Value Chain', code: 'BMGT110', department: 'Business' },
    { name: 'The Intentional Self', code: 'BMGT160', department: 'Business' },
    { name: 'Creative Problem Solving', code: 'BMGT161', department: 'Business' },
    { name: 'Financial Accounting', code: 'BMGT230', department: 'Business' },
    { name: 'Managerial Accounting', code: 'BMGT231', department: 'Business' },
    { name: 'Organizational Behavior', code: 'BMGT301', department: 'Business' },
    { name: 'Business Law I', code: 'BMGT320', department: 'Business' },
    { name: 'Marketing Management', code: 'BMGT370', department: 'Business' },
    { name: 'Financial Management', code: 'BMGT411', department: 'Business' },
    { name: 'Strategic Management', code: 'BMGT450', department: 'Business' },
  ],

  // JOHNS HOPKINS UNIVERSITY (Research University - 68 courses)
  JHU: [
    // Computer Science (15 courses)
    { name: 'Computer Science Foundations I', code: 'EN.601.101', department: 'Computer Science' },
    { name: 'Computer Science Foundations II', code: 'EN.601.102', department: 'Computer Science' },
    { name: 'Intermediate Programming', code: 'EN.601.220', department: 'Computer Science' },
    { name: 'Data Structures', code: 'EN.601.226', department: 'Computer Science' },
    { name: 'Computer Architecture', code: 'EN.601.241', department: 'Computer Science' },
    { name: 'Systems Programming', code: 'EN.601.414', department: 'Computer Science' },
    { name: 'Operating Systems', code: 'EN.601.415', department: 'Computer Science' },
    { name: 'Database Management Systems', code: 'EN.601.316', department: 'Computer Science' },
    { name: 'Computer Algorithms', code: 'EN.601.433', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'EN.601.436', department: 'Computer Science' },
    { name: 'Network Security', code: 'EN.601.443', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'EN.601.461', department: 'Computer Science' },
    { name: 'Human-Computer Interaction', code: 'EN.601.468', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'EN.601.475', department: 'Computer Science' },
    { name: 'Bioinformatics', code: 'EN.601.485', department: 'Computer Science' },

    // Mathematics (12 courses)
    { name: 'Calculus I', code: 'AS.110.108', department: 'Mathematics' },
    { name: 'Calculus II', code: 'AS.110.109', department: 'Mathematics' },
    { name: 'Multivariable Calculus', code: 'AS.110.202', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'AS.110.201', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'AS.110.302', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'EN.601.230', department: 'Mathematics' },
    { name: 'Abstract Algebra I', code: 'AS.110.401', department: 'Mathematics' },
    { name: 'Real Analysis I', code: 'AS.110.405', department: 'Mathematics' },
    { name: 'Complex Analysis', code: 'AS.110.406', department: 'Mathematics' },
    { name: 'Topology', code: 'AS.110.411', department: 'Mathematics' },
    { name: 'Probability and Statistics', code: 'AS.110.106', department: 'Mathematics' },
    { name: 'Numerical Methods', code: 'EN.553.291', department: 'Mathematics' },

    // Physics (12 courses)
    { name: 'Physics I: Mechanics', code: 'AS.171.101', department: 'Physics' },
    { name: 'Physics II: E&M', code: 'AS.171.102', department: 'Physics' },
    { name: 'Physics III: Waves and Modern', code: 'AS.171.103', department: 'Physics' },
    { name: 'Physics Lab I', code: 'AS.171.105', department: 'Physics' },
    { name: 'Physics Lab II', code: 'AS.171.106', department: 'Physics' },
    { name: 'Classical Mechanics I', code: 'AS.171.301', department: 'Physics' },
    { name: 'Electromagnetism I', code: 'AS.171.303', department: 'Physics' },
    { name: 'Modern Physics', code: 'AS.171.201', department: 'Physics' },
    { name: 'Quantum Mechanics I', code: 'AS.171.401', department: 'Physics' },
    { name: 'Thermodynamics', code: 'AS.171.304', department: 'Physics' },
    { name: 'Astrophysics', code: 'AS.171.221', department: 'Physics' },
    { name: 'Biophysics', code: 'AS.250.201', department: 'Physics' },

    // Chemistry (12 courses)
    { name: 'General Chemistry I', code: 'AS.030.103', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'AS.030.104', department: 'Chemistry' },
    { name: 'Organic Chemistry I', code: 'AS.030.205', department: 'Chemistry' },
    { name: 'Organic Chemistry II', code: 'AS.030.206', department: 'Chemistry' },
    { name: 'Physical Chemistry I', code: 'AS.030.307', department: 'Chemistry' },
    { name: 'Physical Chemistry II', code: 'AS.030.308', department: 'Chemistry' },
    { name: 'Analytical Chemistry', code: 'AS.030.227', department: 'Chemistry' },
    { name: 'Biochemistry I', code: 'AS.030.401', department: 'Chemistry' },
    { name: 'Biochemistry II', code: 'AS.030.402', department: 'Chemistry' },
    { name: 'Inorganic Chemistry', code: 'AS.030.309', department: 'Chemistry' },
    { name: 'Chemical Lab I', code: 'AS.030.111', department: 'Chemistry' },
    { name: 'Chemical Lab II', code: 'AS.030.112', department: 'Chemistry' },

    // Biology (12 courses)
    { name: 'General Biology I', code: 'AS.020.151', department: 'Biology' },
    { name: 'General Biology II', code: 'AS.020.152', department: 'Biology' },
    { name: 'Cell Biology', code: 'AS.020.311', department: 'Biology' },
    { name: 'Molecular Biology', code: 'AS.020.362', department: 'Biology' },
    { name: 'Genetics', code: 'AS.020.331', department: 'Biology' },
    { name: 'Ecology', code: 'AS.020.385', department: 'Biology' },
    { name: 'Evolution', code: 'AS.020.371', department: 'Biology' },
    { name: 'Vertebrate Anatomy', code: 'AS.020.307', department: 'Biology' },
    { name: 'Plant Biology', code: 'AS.020.321', department: 'Biology' },
    { name: 'Microbiology', code: 'AS.020.301', department: 'Biology' },
    { name: 'Neuroscience Foundations', code: 'AS.080.101', department: 'Neuroscience' },
    { name: 'Developmental Biology', code: 'AS.020.303', department: 'Biology' },

    // English and Writing (11 courses)
    { name: 'Academic Writing', code: 'AS.220.101', department: 'Writing' },
    { name: 'Poetry Writing', code: 'AS.220.201', department: 'Writing' },
    { name: 'Prose Writing', code: 'AS.220.202', department: 'Writing' },
    { name: 'American Literature I', code: 'AS.060.151', department: 'English' },
    { name: 'American Literature II', code: 'AS.060.152', department: 'English' },
    { name: 'British Literature I', code: 'AS.060.161', department: 'English' },
    { name: 'British Literature II', code: 'AS.060.162', department: 'English' },
    { name: 'Shakespeare', code: 'AS.060.220', department: 'English' },
    { name: 'World Literature', code: 'AS.060.175', department: 'English' },
    { name: 'Modern American Fiction', code: 'AS.060.251', department: 'English' },
    { name: 'Literary Theory', code: 'AS.060.311', department: 'English' },

    // History (10 courses)
    { name: 'World History I', code: 'AS.100.110', department: 'History' },
    { name: 'World History II', code: 'AS.100.111', department: 'History' },
    { name: 'American History I', code: 'AS.100.121', department: 'History' },
    { name: 'American History II', code: 'AS.100.122', department: 'History' },
    { name: 'European History I', code: 'AS.100.131', department: 'History' },
    { name: 'European History II', code: 'AS.100.132', department: 'History' },
    { name: 'Asian History', code: 'AS.100.141', department: 'History' },
    { name: 'History of Science', code: 'AS.140.105', department: 'History' },
    { name: 'African History', code: 'AS.100.151', department: 'History' },
    { name: 'Latin American History', code: 'AS.100.152', department: 'History' },
  ],

  // UMBC (40 courses)
  UMBC: [
    { name: 'Introduction to Computer Science I', code: 'CMSC201', department: 'Computer Science' },
    { name: 'Introduction to Computer Science II', code: 'CMSC202', department: 'Computer Science' },
    { name: 'Discrete Structures', code: 'CMSC203', department: 'Computer Science' },
    { name: 'Computer Organization', code: 'CMSC313', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CMSC341', department: 'Computer Science' },
    { name: 'Algorithms', code: 'CMSC441', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'CMSC345', department: 'Computer Science' },
    { name: 'Database Management', code: 'CMSC461', department: 'Computer Science' },
    { name: 'Operating Systems', code: 'CMSC421', department: 'Computer Science' },
    { name: 'Web Development', code: 'CMSC331', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH151', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH152', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH221', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'MATH281', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'MATH251', department: 'Mathematics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Organic Chemistry I', code: 'CHEM231', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS121', department: 'Physics' },
    { name: 'Physics II', code: 'PHYS122', department: 'Physics' },
    { name: 'Biology I', code: 'BIOL100', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Rhetoric', code: 'ENGL201', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC100', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON101', department: 'Economics' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Technical Communication', code: 'ENGL393', department: 'English' },
    { name: 'Statistics for Scientists', code: 'STAT355', department: 'Statistics' },
    { name: 'Information Systems', code: 'CMSC380', department: 'Computer Science' },
    { name: 'Computer Networks', code: 'CMSC411', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'CMSC451', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'CMSC471', department: 'Computer Science' },
    { name: 'Data Mining', code: 'CMSC491', department: 'Computer Science' },
    { name: 'Business Law', code: 'BUSN301', department: 'Business' },
    { name: 'Marketing Principles', code: 'MKTG201', department: 'Marketing' },
    { name: 'Accounting Principles I', code: 'ACCT201', department: 'Accounting' },
    { name: 'Management Essentials', code: 'MGMT201', department: 'Management' },
  ],

  // TOWSON UNIVERSITY (25 courses)
  TU: [
    { name: 'Computer Science I', code: 'COSC101', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'COSC102', department: 'Computer Science' },
    { name: 'Data Structures', code: 'COSC201', department: 'Computer Science' },
    { name: 'Database Systems', code: 'COSC301', department: 'Computer Science' },
    { name: 'Web Programming', code: 'COSC311', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'COSC340', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH115', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH116', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH213', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'MATH215', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS155', department: 'Physics' },
    { name: 'General Physics II', code: 'PHYS156', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL102', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature Survey', code: 'ENGL201', department: 'English' },
    { name: 'American History I', code: 'HIST101', department: 'History' },
    { name: 'American History II', code: 'HIST102', department: 'History' },
    { name: 'World History I', code: 'HIST103', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON103', department: 'Economics' },
    { name: 'Introductory Business', code: 'MGMT101', department: 'Management' },
    { name: 'Accounting Principles I', code: 'ACCT101', department: 'Accounting' },
  ],

  // MORGAN STATE UNIVERSITY (20 courses)
  Morgan: [
    { name: 'Introduction to Computer Science', code: 'CSCI111', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'CSCI112', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CSCI211', department: 'Computer Science' },
    { name: 'Programming Concepts', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH132', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH231', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS200', department: 'Physics' },
    { name: 'General Physics II', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL102', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Culture', code: 'ENGL201', department: 'English' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'African American History', code: 'HIST315', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Macroeconomics', code: 'ECON202', department: 'Economics' },
  ],

  // BOWIE STATE UNIVERSITY (14 courses)
  Bowie: [
    { name: 'Intro to Computer Science', code: 'CSCI101', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'CSCI102', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CSCI201', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH122', department: 'Mathematics' },
    { name: 'Physics for Engineers', code: 'PHYS211', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'General Economics', code: 'ECON101', department: 'Economics' },
    { name: 'Business Management', code: 'MGMT101', department: 'Management' },
  ],

  // COPPIN STATE UNIVERSITY (12 courses)
  Coppin: [
    { name: 'Introduction to Computer Science', code: 'CS101', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS105', department: 'Computer Science' },
    { name: 'Programming II', code: 'CS106', department: 'Computer Science' },
    { name: 'Web Development', code: 'CS210', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'General Physics', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Introduction to Economics', code: 'ECON101', department: 'Economics' },
  ],

  // SALISBURY UNIVERSITY (15 courses)
  SU: [
    { name: 'Computer Science I', code: 'COSC171', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'COSC172', department: 'Computer Science' },
    { name: 'Data Structures', code: 'COSC250', department: 'Computer Science' },
    { name: 'Database Management', code: 'COSC470', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH161', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH162', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH260', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS161', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM191', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL161', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American Literature', code: 'ENGL321', department: 'English' },
    { name: 'U.S. History I', code: 'HIST105', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
  ],

  // FROSTBURG STATE UNIVERSITY (11 courses)
  FSU: [
    { name: 'Introduction to CS', code: 'CSCI100', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Programming II', code: 'CSCI106', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS150', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM150', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL150', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics I', code: 'ECON101', department: 'Economics' },
  ],

  // UNIVERSITY OF BALTIMORE (10 courses)
  UBalt: [
    { name: 'Introduction to Programming', code: 'CMPT101', department: 'Information Technology' },
    { name: 'Web Development', code: 'CMPT201', department: 'Information Technology' },
    { name: 'Database Fundamentals', code: 'CMPT210', department: 'Information Technology' },
    { name: 'Business Mathematics', code: 'MATH101', department: 'Mathematics' },
    { name: 'Technical Writing', code: 'ENGL200', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Organizational Behavior', code: 'MGMT201', department: 'Management' },
    { name: 'Financial Accounting', code: 'ACCT201', department: 'Accounting' },
    { name: 'Business Law', code: 'LAW201', department: 'Business Law' },
    { name: 'Marketing Principles', code: 'MKTG201', department: 'Marketing' },
  ],

  // UNIVERSITY OF MARYLAND EASTERN SHORE (10 courses)
  UMES: [
    { name: 'Introduction to CS', code: 'CSCI101', department: 'Computer Science' },
    { name: 'Programming Fundamentals', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'General Physics', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'History', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics', code: 'ECON101', department: 'Economics' },
  ],

  // UNIVERSITY OF MARYLAND GLOBAL CAMPUS (8 courses)
  UMGC: [
    { name: 'Introduction to Technology', code: 'ITEC101', department: 'Information Technology' },
    { name: 'Business Management', code: 'MGMT301', department: 'Management' },
    { name: 'Financial Accounting', code: 'ACCT311', department: 'Accounting' },
    { name: 'Business Law', code: 'CMIT301', department: 'Information Technology' },
    { name: 'Database Design', code: 'CMIT415', department: 'Information Technology' },
    { name: 'Business Communications', code: 'COMM101', department: 'Communication' },
    { name: 'Economics for Managers', code: 'ECON201', department: 'Economics' },
    { name: 'Organizational Behavior', code: 'MGMT325', department: 'Management' },
  ],

  // ST. MARY'S COLLEGE OF MARYLAND (10 courses)
  SMCM: [
    { name: 'Introduction to Computer Science', code: 'CS100', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS150', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH151', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'Composition and Literature', code: 'ENGL101', department: 'English' },
    { name: 'World History I', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON101', department: 'Economics' },
  ],

  // UNITED STATES NAVAL ACADEMY (10 courses)
  USNA: [
    { name: 'Calculus I', code: 'SM101', department: 'Mathematics' },
    { name: 'Calculus II', code: 'SM102', department: 'Mathematics' },
    { name: 'Physics I', code: 'PH101', department: 'Physics' },
    { name: 'Physics II', code: 'PH102', department: 'Physics' },
    { name: 'Chemistry I', code: 'CH101', department: 'Chemistry' },
    { name: 'Engineering Graphics', code: 'EN101', department: 'Engineering' },
    { name: 'Naval Engineering', code: 'EN201', department: 'Engineering' },
    { name: 'English Composition', code: 'EN100', department: 'English' },
    { name: 'American History', code: 'HI101', department: 'History' },
    { name: 'Seamanship', code: 'NP101', department: 'Naval Procedures' },
  ],

  // LOYOLA UNIVERSITY MARYLAND (17 courses)
  Loyola: [
    { name: 'Introduction to Computer Science', code: 'CSCI101', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI110', department: 'Computer Science' },
    { name: 'Programming II', code: 'CSCI111', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CSCI210', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH132', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS150', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Society', code: 'ENGL201', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'World Religions', code: 'THOL101', department: 'Theology' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Business Law I', code: 'BUSN301', department: 'Business' },
    { name: 'Accounting Principles', code: 'ACCT301', department: 'Accounting' },
  ],

  // MCDANIEL COLLEGE (13 courses)
  McDaniel: [
    { name: 'Introduction to Computer Science', code: 'CS105', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CS205', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'Composition and Rhetoric', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Culture', code: 'ENGL201', department: 'English' },
    { name: 'U.S. History I', code: 'HIST151', department: 'History' },
    { name: 'World History I', code: 'HIST101', department: 'History' },
    { name: 'Psychology of Learning', code: 'PSYC201', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON101', department: 'Economics' },
    { name: 'Business Administration', code: 'BUSN101', department: 'Business' },
  ],

  // HOOD COLLEGE (12 courses)
  Hood: [
    { name: 'Introduction to Computer Science', code: 'CS110', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS150', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics Principles', code: 'ECON101', department: 'Economics' },
    { name: 'Business Foundations', code: 'BUSN101', department: 'Business' },
    { name: 'Studio Art I', code: 'ART101', department: 'Art' },
  ],

  // GOUCHER COLLEGE (13 courses)
  Goucher: [
    { name: 'Introduction to Computer Science', code: 'CS105', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS150', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL100', department: 'English' },
    { name: 'Literature Seminar', code: 'ENGL200', department: 'English' },
    { name: 'American History', code: 'HIST150', department: 'History' },
    { name: 'World History', code: 'HIST100', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON101', department: 'Economics' },
    { name: 'Contemporary Issues', code: 'POLS101', department: 'Political Science' },
  ],

  // MOUNT ST. MARY'S UNIVERSITY (11 courses)
  MSM: [
    { name: 'Introduction to CS', code: 'CSCI110', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI150', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'Composition I', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Christian Theology', code: 'THEL101', department: 'Theology' },
    { name: 'Psychology I', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics I', code: 'ECON101', department: 'Economics' },
  ],

  // WASHINGTON COLLEGE (12 courses)
  WashCol: [
    { name: 'Introduction to Computer Science', code: 'CS105', department: 'Computer Science' },
    { name: 'Programming Fundamentals', code: 'CS110', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American Literature', code: 'ENGL250', department: 'English' },
    { name: 'U.S. History I', code: 'HIST151', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics Principles', code: 'ECON101', department: 'Economics' },
    { name: 'Environmental Studies', code: 'ENVS101', department: 'Environmental Science' },
  ],

  // STEVENSON UNIVERSITY (13 courses)
  Stevenson: [
    { name: 'Introduction to Computer Science', code: 'CS110', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS150', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CS250', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS150', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM151', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL151', department: 'Biology' },
    { name: 'Writing and Rhetoric', code: 'ENGL101', department: 'English' },
    { name: 'American History', code: 'HIST151', department: 'History' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Business Fundamentals', code: 'BUSN101', department: 'Business' },
    { name: 'Marketing Essentials', code: 'MKTG201', department: 'Marketing' },
  ],

  // NOTRE DAME OF MARYLAND UNIVERSITY (13 courses)
  NDMU: [
    { name: 'Introduction to Computer Science', code: 'CS105', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS150', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS150', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM150', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL150', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Women and Literature', code: 'ENGL250', department: 'English' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Christian Ethics', code: 'THOL201', department: 'Theology' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Nursing Fundamentals', code: 'NURS101', department: 'Nursing' },
    { name: 'Health Care Ethics', code: 'NURS200', department: 'Nursing' },
  ],

  // MONTGOMERY COLLEGE - Community College (14 courses)
  MC: [
    { name: 'Programming Fundamentals I', code: 'CMSC110', department: 'Computer Science' },
    { name: 'Programming Fundamentals II', code: 'CMSC111', department: 'Computer Science' },
    { name: 'Web Development', code: 'CMSC130', department: 'Computer Science' },
    { name: 'College Algebra', code: 'MATH120', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH161', department: 'Mathematics' },
    { name: 'General Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS141', department: 'Physics' },
    { name: 'English Composition I', code: 'ENGL101', department: 'English' },
    { name: 'American History I', code: 'HIST141', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Introduction to Business', code: 'BUSN105', department: 'Business' },
    { name: 'Accounting Principles', code: 'ACCT101', department: 'Accounting' },
  ],

  // PRINCE GEORGE'S COMMUNITY COLLEGE (13 courses)
  PGCC: [
    { name: 'Introduction to Programming', code: 'COIT100', department: 'Computer Science' },
    { name: 'Programming I', code: 'COIT110', department: 'Computer Science' },
    { name: 'Programming II', code: 'COIT111', department: 'Computer Science' },
    { name: 'College Algebra', code: 'MATH110', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH160', department: 'Mathematics' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS140', department: 'Physics' },
    { name: 'English Composition I', code: 'ENGL101', department: 'English' },
    { name: 'World History I', code: 'HIST151', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Macroeconomics', code: 'ECON202', department: 'Economics' },
    { name: 'Business Management', code: 'BUSN101', department: 'Business' },
  ],

  // COMMUNITY COLLEGE OF BALTIMORE COUNTY (14 courses)
  CCBC: [
    { name: 'Introduction to Computing', code: 'COMP110', department: 'Computer Science' },
    { name: 'Programming Concepts', code: 'COMP130', department: 'Computer Science' },
    { name: 'Web Development Fundamentals', code: 'COMP140', department: 'Computer Science' },
    { name: 'Intermediate Algebra', code: 'MATH070', department: 'Mathematics' },
    { name: 'College Algebra', code: 'MATH115', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH160', department: 'Mathematics' },
    { name: 'General Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS140', department: 'Physics' },
    { name: 'English Composition I', code: 'ENGL101', department: 'English' },
    { name: 'American History I', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Business Math', code: 'MATH140', department: 'Mathematics' },
    { name: 'Accounting Fundamentals', code: 'ACCT101', department: 'Accounting' },
  ],

  // ANNE ARUNDEL COMMUNITY COLLEGE (13 courses)
  AACC: [
    { name: 'Computer Concepts I', code: 'CSCI110', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI120', department: 'Computer Science' },
    { name: 'Programming II', code: 'CSCI121', department: 'Computer Science' },
    { name: 'College Algebra', code: 'MATH100', department: 'Mathematics' },
    { name: 'Precalculus', code: 'MATH130', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH150', department: 'Mathematics' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics for Life Science', code: 'PHYS110', department: 'Physics' },
    { name: 'English Composition I', code: 'ENGL101', department: 'English' },
    { name: 'U.S. History to 1865', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Business Law', code: 'BUSN140', department: 'Business' },
  ],

  // HOWARD COMMUNITY COLLEGE (13 courses)
  HCC: [
    { name: 'Introduction to Programming', code: 'CIST100', department: 'Computer Science' },
    { name: 'Programming Fundamentals I', code: 'CIST110', department: 'Computer Science' },
    { name: 'Web Design I', code: 'CIST140', department: 'Computer Science' },
    { name: 'College Algebra', code: 'MATH090', department: 'Mathematics' },
    { name: 'Precalculus', code: 'MATH120', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'General Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS161', department: 'Physics' },
    { name: 'Composition I', code: 'ENGL101', department: 'English' },
    { name: 'American History I', code: 'HIST121', department: 'History' },
    { name: 'Intro to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Accounting Principles', code: 'ACCT101', department: 'Accounting' },
  ],

  // FREDERICK COMMUNITY COLLEGE (13 courses)
  FCC: [
    { name: 'Introduction to Computers', code: 'COMP100', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSIS110', department: 'Computer Science' },
    { name: 'Internet Fundamentals', code: 'CSIS140', department: 'Computer Science' },
    { name: 'Basic Algebra', code: 'MATH050', department: 'Mathematics' },
    { name: 'College Algebra', code: 'MATH100', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH140', department: 'Mathematics' },
    { name: 'Biology I', code: 'BIOL111', department: 'Biology' },
    { name: 'Chemistry I', code: 'CHEM111', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS141', department: 'Physics' },
    { name: 'Writing I', code: 'ENGL101', department: 'English' },
    { name: 'American History I', code: 'HIST104', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Intro to Business', code: 'BUSN101', department: 'Business' },
  ],

  // HARFORD COMMUNITY COLLEGE (12 courses)
  Harford: [
    { name: 'Introduction to IT', code: 'ISDM101', department: 'Information Technology' },
    { name: 'Programming I', code: 'ISDM110', department: 'Information Technology' },
    { name: 'Web Development I', code: 'ISDM120', department: 'Information Technology' },
    { name: 'College Algebra', code: 'MATH100', department: 'Mathematics' },
    { name: 'Precalculus', code: 'MATH115', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH130', department: 'Mathematics' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS151', department: 'Physics' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'History I', code: 'HIST101', department: 'History' },
    { name: 'Intro to Psychology', code: 'PSYC101', department: 'Psychology' },
  ],

  // CARROLL COMMUNITY COLLEGE (12 courses)
  Carroll: [
    { name: 'Introduction to Programming', code: 'CS100', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS110', department: 'Computer Science' },
    { name: 'Web Development', code: 'CS140', department: 'Computer Science' },
    { name: 'Intermediate Algebra', code: 'MATH050', department: 'Mathematics' },
    { name: 'College Algebra', code: 'MATH110', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH160', department: 'Mathematics' },
    { name: 'Biology', code: 'BIOL101', department: 'Biology' },
    { name: 'Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics', code: 'PHYS121', department: 'Physics' },
    { name: 'Composition', code: 'ENGL101', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
  ],

  // COLLEGE OF SOUTHERN MARYLAND (12 courses)
  CSM: [
    { name: 'Intro to Computers', code: 'CSIT101', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSIT110', department: 'Computer Science' },
    { name: 'Web Design Basics', code: 'CSIT140', department: 'Computer Science' },
    { name: 'Basic Math', code: 'MATH032', department: 'Mathematics' },
    { name: 'College Algebra', code: 'MATH105', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH150', department: 'Mathematics' },
    { name: 'Biology', code: 'BIOL101', department: 'Biology' },
    { name: 'Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Physics', code: 'PHYS121', department: 'Physics' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Intro to Psychology', code: 'PSYC101', department: 'Psychology' },
  ],

  // DEFAULT courses for schools without specific listings
  DEFAULT: [
    { name: 'Calculus I', code: 'MATH101', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH102', department: 'Mathematics' },
    { name: 'Intro to Computer Science', code: 'CS101', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CS201', department: 'Computer Science' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Physics I', code: 'PHYS101', department: 'Physics' },
    { name: 'Intro to Biology', code: 'BIO101', department: 'Biology' },
    { name: 'Microeconomics', code: 'ECON101', department: 'Economics' },
    { name: 'Statistics', code: 'STAT101', department: 'Statistics' },
    { name: 'Technical Writing', code: 'ENG201', department: 'English' },
  ],
}

module.exports = {
  SCHOOLS,
  COURSES,
}
