const SCHOOLS = [
  { name: 'University of Maryland, College Park', short: 'UMD' },
  { name: 'UMBC', short: 'UMBC' },
  { name: 'Towson University', short: 'TU' },
  { name: 'Morgan State University', short: 'Morgan' },
  { name: 'Bowie State University', short: 'Bowie' },
  { name: 'Coppin State University', short: 'Coppin' },
  { name: 'Salisbury University', short: 'SU' },
  { name: 'Frostburg State University', short: 'FSU' },
  { name: 'University of Baltimore', short: 'UBalt' },
  { name: 'Johns Hopkins University', short: 'JHU' },
  { name: 'Loyola University Maryland', short: 'Loyola' },
  { name: 'McDaniel College', short: 'McDaniel' },
  { name: 'Hood College', short: 'Hood' },
  { name: 'Goucher College', short: 'Goucher' },
  { name: "St. Mary's College of Maryland", short: 'SMCM' },
]

const COURSES = {
  UMD: [
    { name: 'Calculus I', code: 'MATH140' },
    { name: 'Calculus II', code: 'MATH141' },
    { name: 'Calculus III', code: 'MATH241' },
    { name: 'Linear Algebra', code: 'MATH240' },
    { name: 'Intro to Computer Science', code: 'CMSC131' },
    { name: 'Object-Oriented Programming', code: 'CMSC132' },
    { name: 'Discrete Math', code: 'CMSC250' },
    { name: 'Data Structures', code: 'CMSC420' },
    { name: 'Algorithms', code: 'CMSC351' },
    { name: 'Computer Architecture', code: 'CMSC411' },
    { name: 'Operating Systems', code: 'CMSC412' },
    { name: 'Intro to Biology', code: 'BSCI105' },
    { name: 'General Chemistry I', code: 'CHEM131' },
    { name: 'General Chemistry II', code: 'CHEM132' },
    { name: 'General Physics I', code: 'PHYS141' },
    { name: 'General Physics II', code: 'PHYS142' },
    { name: 'Macroeconomics', code: 'ECON201' },
    { name: 'Microeconomics', code: 'ECON200' },
    { name: 'Statistics', code: 'STAT400' },
    { name: 'Technical Writing', code: 'ENGL393' },
  ],
  UMBC: [
    { name: 'Intro to Computing', code: 'CMSC201' },
    { name: 'Computer Science II', code: 'CMSC202' },
    { name: 'Discrete Structures', code: 'CMSC203' },
    { name: 'Computer Organization', code: 'CMSC313' },
    { name: 'Data Structures', code: 'CMSC341' },
    { name: 'Algorithms', code: 'CMSC441' },
    { name: 'Software Engineering', code: 'CMSC345' },
    { name: 'Database Management', code: 'CMSC461' },
    { name: 'Operating Systems', code: 'CMSC421' },
    { name: 'Calculus I', code: 'MATH151' },
    { name: 'Calculus II', code: 'MATH152' },
    { name: 'Linear Algebra', code: 'MATH221' },
    { name: 'General Chemistry I', code: 'CHEM101' },
    { name: 'General Physics I', code: 'PHYS121' },
    { name: 'Statistics for Scientists', code: 'STAT355' },
    { name: 'Intro to Biology', code: 'BIOL100' },
    { name: 'Principles of Economics', code: 'ECON101' },
    { name: 'Technical Communication', code: 'ENGL393' },
  ],
  TU: [
    { name: 'Intro to Computer Science', code: 'COSC175' },
    { name: 'Data Structures', code: 'COSC290' },
    { name: 'Computer Organization', code: 'COSC340' },
    { name: 'Algorithms', code: 'COSC455' },
    { name: 'Calculus I', code: 'MATH273' },
    { name: 'Calculus II', code: 'MATH274' },
    { name: 'General Chemistry', code: 'CHEM110' },
    { name: 'General Biology', code: 'BIOL110' },
    { name: 'Intro to Psychology', code: 'PSYC101' },
    { name: 'Principles of Accounting', code: 'ACCT201' },
  ],
  DEFAULT: [
    { name: 'Calculus I', code: 'MATH101' },
    { name: 'Calculus II', code: 'MATH102' },
    { name: 'Intro to Computer Science', code: 'CS101' },
    { name: 'Data Structures', code: 'CS201' },
    { name: 'General Chemistry I', code: 'CHEM101' },
    { name: 'General Physics I', code: 'PHYS101' },
    { name: 'Intro to Biology', code: 'BIO101' },
    { name: 'Microeconomics', code: 'ECON101' },
    { name: 'Statistics', code: 'STAT101' },
    { name: 'Technical Writing', code: 'ENG201' },
  ],
}

module.exports = {
  SCHOOLS,
  COURSES,
}
