const ERROR_CODES = Object.freeze({
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_MFA_REQUIRED: 'ADMIN_MFA_REQUIRED',
  CSRF_INVALID: 'CSRF_INVALID',
  GUARDED_MODE: 'GUARDED_MODE',
  PREVIEW_TOKEN_INVALID: 'PREVIEW_TOKEN_INVALID',
  PREVIEW_HTML_BLOCKED: 'PREVIEW_HTML_BLOCKED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  UPLOAD_MISSING_FILE: 'UPLOAD_MISSING_FILE',
  UPLOAD_SAVE_FAILED: 'UPLOAD_SAVE_FAILED',
  UPLOAD_SIGNATURE_MISMATCH: 'UPLOAD_SIGNATURE_MISMATCH',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
  SUPER_ADMIN_PROTECTED: 'SUPER_ADMIN_PROTECTED',
  SERVER_ERROR: 'SERVER_ERROR',
})

function sendError(res, status, error, code, extra = {}) {
  return res.status(status).json({
    error,
    code,
    ...extra,
  })
}

module.exports = {
  ERROR_CODES,
  sendError,
}
